import { defineConfig } from 'vitest/config'
import path from 'path'

const modulesDir = path.resolve(__dirname, 'node_modules')
const radixDir = path.join(modulesDir, '@radix-ui')

export default defineConfig({
  resolve: {
    alias: [
      { find: '@', replacement: path.resolve(__dirname, './') },
      // Motores (packages/rewards, packages/mr519): resolver deps desde la app
      // (más específicos primero; el orden importa en la coincidencia por prefijo)
      { find: 'viem/accounts', replacement: path.join(modulesDir, 'viem/_esm/accounts/index.js') },
      { find: 'viem/chains', replacement: path.join(modulesDir, 'viem/_esm/chains/index.js') },
      { find: 'viem', replacement: path.join(modulesDir, 'viem') },
      { find: '@pasosdejesus/m/blockchain/deployments', replacement: path.join(modulesDir, '@pasosdejesus', 'm', 'dist', 'blockchain', 'deployments.js') },
      { find: '@pasosdejesus/m/test-utils/kysely-mocks', replacement: path.join(modulesDir, '@pasosdejesus', 'm', 'dist', 'test-utils', 'kysely-mocks.js') },
      { find: '@pasosdejesus/mpdj/test-utils', replacement: path.join(modulesDir, '@pasosdejesus', 'mpdj', 'dist', 'test-utils', 'blockchain-mocks.js') },
      { find: '@pasosdejesus/mpdj/blockchain/ecosystem-addresses', replacement: path.join(modulesDir, '@pasosdejesus', 'mpdj', 'dist', 'blockchain', 'ecosystem-addresses.js') },
      { find: '@pasosdejesus/mpdj/blockchain', replacement: path.join(modulesDir, '@pasosdejesus', 'mpdj', 'dist', 'blockchain', 'index.js') },
      { find: '@pasosdejesus/usdt/lib/donate-utils', replacement: path.join(modulesDir, '@pasosdejesus', 'usdt', 'dist', 'lib', 'donate-utils.js') },
      { find: '@pasosdejesus/usdt/lib/parse-wallet-error', replacement: path.join(modulesDir, '@pasosdejesus', 'usdt', 'dist', 'lib', 'parse-wallet-error.js') },
      { find: '@pasosdejesus/usdt/hooks/useGasEstimation', replacement: path.join(modulesDir, '@pasosdejesus', 'usdt', 'dist', 'hooks', 'useGasEstimation.js') },
      { find: '@pasosdejesus/usdt/hooks/useContractPayment', replacement: path.join(modulesDir, '@pasosdejesus', 'usdt', 'dist', 'hooks', 'useContractPayment.js') },
      { find: '@pasosdejesus/usdt/components/TransactionStatus', replacement: path.join(modulesDir, '@pasosdejesus', 'usdt', 'dist', 'components', 'TransactionStatus.js') },
      { find: 'dotenv/config', replacement: path.join(modulesDir, 'dotenv/config.js') },
      { find: 'dotenv', replacement: path.join(modulesDir, 'dotenv') },
      { find: 'next/server', replacement: path.join(modulesDir, 'next/server.js') },
      { find: 'next', replacement: path.join(modulesDir, 'next') },
      { find: 'kysely', replacement: path.join(modulesDir, 'kysely') },
      // React — una sola instancia desde el node_modules de learn.tg
      { find: 'react', replacement: path.join(modulesDir, 'react') },
      { find: 'react-dom', replacement: path.join(modulesDir, 'react-dom') },
      // Radix UI
      { find: '@radix-ui/react-accordion', replacement: path.join(radixDir, 'react-accordion') },
      { find: '@radix-ui/react-alert-dialog', replacement: path.join(radixDir, 'react-alert-dialog') },
      { find: '@radix-ui/react-arrow', replacement: path.join(radixDir, 'react-arrow') },
      { find: '@radix-ui/react-avatar', replacement: path.join(radixDir, 'react-avatar') },
      { find: '@radix-ui/react-checkbox', replacement: path.join(radixDir, 'react-checkbox') },
      { find: '@radix-ui/react-collection', replacement: path.join(radixDir, 'react-collection') },
      { find: '@radix-ui/react-compose-refs', replacement: path.join(radixDir, 'react-compose-refs') },
      { find: '@radix-ui/react-context', replacement: path.join(radixDir, 'react-context') },
      { find: '@radix-ui/react-dialog', replacement: path.join(radixDir, 'react-dialog') },
      { find: '@radix-ui/react-direction', replacement: path.join(radixDir, 'react-direction') },
      { find: '@radix-ui/react-dismissable-layer', replacement: path.join(radixDir, 'react-dismissable-layer') },
      { find: '@radix-ui/react-dropdown-menu', replacement: path.join(radixDir, 'react-dropdown-menu') },
      { find: '@radix-ui/react-focus-guards', replacement: path.join(radixDir, 'react-focus-guards') },
      { find: '@radix-ui/react-focus-scope', replacement: path.join(radixDir, 'react-focus-scope') },
      { find: '@radix-ui/react-id', replacement: path.join(radixDir, 'react-id') },
      { find: '@radix-ui/react-label', replacement: path.join(radixDir, 'react-label') },
      { find: '@radix-ui/react-menu', replacement: path.join(radixDir, 'react-menu') },
      { find: '@radix-ui/react-menubar', replacement: path.join(radixDir, 'react-menubar') },
      { find: '@radix-ui/react-popover', replacement: path.join(radixDir, 'react-popover') },
      { find: '@radix-ui/react-popper', replacement: path.join(radixDir, 'react-popper') },
      { find: '@radix-ui/react-portal', replacement: path.join(radixDir, 'react-portal') },
      { find: '@radix-ui/react-presence', replacement: path.join(radixDir, 'react-presence') },
      { find: '@radix-ui/react-primitive', replacement: path.join(radixDir, 'react-primitive') },
      { find: '@radix-ui/react-progress', replacement: path.join(radixDir, 'react-progress') },
      { find: '@radix-ui/react-radio-group', replacement: path.join(radixDir, 'react-radio-group') },
      { find: '@radix-ui/react-roving-focus', replacement: path.join(radixDir, 'react-roving-focus') },
      { find: '@radix-ui/react-scroll-area', replacement: path.join(radixDir, 'react-scroll-area') },
      { find: '@radix-ui/react-select', replacement: path.join(radixDir, 'react-select') },
      { find: '@radix-ui/react-separator', replacement: path.join(radixDir, 'react-separator') },
      { find: '@radix-ui/react-slider', replacement: path.join(radixDir, 'react-slider') },
      { find: '@radix-ui/react-slot', replacement: path.join(radixDir, 'react-slot') },
      { find: '@radix-ui/react-switch', replacement: path.join(radixDir, 'react-switch') },
      { find: '@radix-ui/react-tabs', replacement: path.join(radixDir, 'react-tabs') },
      { find: '@radix-ui/react-toast', replacement: path.join(radixDir, 'react-toast') },
      { find: '@radix-ui/react-toggle', replacement: path.join(radixDir, 'react-toggle') },
      { find: '@radix-ui/react-tooltip', replacement: path.join(radixDir, 'react-tooltip') },
      { find: '@radix-ui/react-use-callback-ref', replacement: path.join(radixDir, 'react-use-callback-ref') },
      { find: '@radix-ui/react-use-controllable-state', replacement: path.join(radixDir, 'react-use-controllable-state') },
      { find: '@radix-ui/react-use-escape-keydown', replacement: path.join(radixDir, 'react-use-escape-keydown') },
      { find: '@radix-ui/react-use-layout-effect', replacement: path.join(radixDir, 'react-use-layout-effect') },
      { find: '@radix-ui/react-use-previous', replacement: path.join(radixDir, 'react-use-previous') },
      { find: '@radix-ui/react-use-rect', replacement: path.join(radixDir, 'react-use-rect') },
      { find: '@radix-ui/react-use-size', replacement: path.join(radixDir, 'react-use-size') },
      { find: '@radix-ui/react-visually-hidden', replacement: path.join(radixDir, 'react-visually-hidden') },
      { find: 'lucide-react', replacement: path.join(modulesDir, 'lucide-react') },
      { find: 'react-hook-form', replacement: path.join(modulesDir, 'react-hook-form') },
      { find: 'react-remove-scroll', replacement: path.join(modulesDir, 'react-remove-scroll') },
      { find: 'class-variance-authority', replacement: path.join(modulesDir, 'class-variance-authority') },
      { find: 'clsx', replacement: path.join(modulesDir, 'clsx') },
      { find: 'tailwind-merge', replacement: path.join(modulesDir, 'tailwind-merge') },
    ],
    dedupe: ['react', 'react-dom'],
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    hookTimeout: 30000,
    server: {
      deps: {
        inline: ['lz-string', '@pasosdejesus/m'],
      },
    },
    coverage: {
      reporter: ['text', 'json', 'html'],
    },
    onConsoleLog: (log, type) => type !== 'stderr',
    // Excluir E2E tests — requieren servidor corriendo (solo CI)
    exclude: ['e2e/**', 'node_modules/**'],
  },
  esbuild: {
    jsx: 'automatic',
    jsxImportSource: 'react',
  },
})
