/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ArInternalMetadata {
  created_at: Timestamp;
  key: string;
  updated_at: Timestamp;
  value: string | null;
}

export interface BilleteraUsuario {
  answer_fib: string | null;
  billetera: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  nonce: string | null;
  nonce_expires_at: Timestamp | null;
  token: string | null;
  updated_at: Timestamp;
  usuario_id: number;
}

export interface Cor1440GenActividad {
  created_at: Timestamp | null;
  fecha: Timestamp;
  id: Generated<number>;
  lugar: string | null;
  minutos: number | null;
  nombre: string | null;
  objetivo: string | null;
  observaciones: string | null;
  oficina_id: number;
  resultado: string | null;
  updated_at: Timestamp | null;
  usuario_id: number;
}

export interface Cor1440GenActividadActividadpf {
  actividad_id: number;
  actividadpf_id: number;
}

export interface Cor1440GenActividadActividadtipo {
  actividad_id: number | null;
  actividadtipo_id: number | null;
}

export interface Cor1440GenActividadAnexo {
  actividad_id: number;
  anexo_id: number;
  id: Generated<number>;
}

export interface Cor1440GenActividadarea {
  created_at: Timestamp | null;
  fechacreacion: Generated<Timestamp | null>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenActividadareasActividad {
  actividad_id: number | null;
  actividadarea_id: number | null;
  created_at: Timestamp | null;
  id: Generated<number>;
  updated_at: Timestamp | null;
}

export interface Cor1440GenActividadOrgsocial {
  actividad_id: Int8;
  orgsocial_id: Int8;
}

export interface Cor1440GenActividadpf {
  actividadtipo_id: number | null;
  descripcion: string | null;
  formulario_id: number | null;
  heredade_id: number | null;
  id: Generated<number>;
  nombrecorto: string | null;
  proyectofinanciero_id: number | null;
  resultadopf_id: number | null;
  sufijoRuta: string | null;
  titulo: string | null;
}

export interface Cor1440GenActividadpfMindicadorpf {
  actividadpf_id: number | null;
  mindicadorpf_id: number | null;
}

export interface Cor1440GenActividadProyecto {
  actividad_id: number | null;
  id: Generated<number>;
  proyecto_id: number | null;
}

export interface Cor1440GenActividadProyectofinanciero {
  actividad_id: number;
  id: Generated<number>;
  proyectofinanciero_id: number;
}

export interface Cor1440GenActividadRangoedadac {
  actividad_id: number | null;
  created_at: Timestamp | null;
  fl: number | null;
  fr: number | null;
  id: Generated<number>;
  ml: number | null;
  mr: number | null;
  rangoedadac_id: number | null;
  s: number | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenActividadRespuestafor {
  actividad_id: number;
  respuestafor_id: number;
}

export interface Cor1440GenActividadtipo {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  listadoasistencia: boolean | null;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface Cor1440GenActividadtipoFormulario {
  actividadtipo_id: number;
  formulario_id: number;
}

export interface Cor1440GenActividadUsuario {
  actividad_id: number;
  usuario_id: number;
}

export interface Cor1440GenAnexoEfecto {
  anexo_id: number | null;
  efecto_id: number | null;
  id: Generated<Int8>;
}

export interface Cor1440GenAnexoProyectofinanciero {
  anexo_id: number | null;
  id: Generated<Int8>;
  proyectofinanciero_id: number | null;
}

export interface Cor1440GenAsistencia {
  actividad_id: number;
  externo: boolean | null;
  id: Generated<Int8>;
  orgsocial_id: number | null;
  perfilorgsocial_id: number | null;
  persona_id: number;
  rangoedadac_id: number | null;
}

export interface Cor1440GenBeneficiariopf {
  persona_id: number | null;
  proyectofinanciero_id: number | null;
}

export interface Cor1440GenCaracterizacionpersona {
  id: Generated<Int8>;
  persona_id: number;
  respuestafor_id: number;
  ulteditor_id: number;
}

export interface Cor1440GenCaracterizacionpf {
  formulario_id: number | null;
  proyectofinanciero_id: number | null;
}

export interface Cor1440GenDatointermedioti {
  filtro: string | null;
  funcion: string | null;
  id: Generated<Int8>;
  mindicadorpf_id: number | null;
  nombre: string;
  nombreinterno: string | null;
  tipoindicador_id: number | null;
}

export interface Cor1440GenDatointermediotiPmindicadorpf {
  datointermedioti_id: number;
  id: Generated<Int8>;
  pmindicadorpf_id: number;
  rutaevidencia: string | null;
  valor: number | null;
}

export interface Cor1440GenDesembolso {
  created_at: Timestamp;
  detalle: string | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinanciero_id: number;
  updated_at: Timestamp;
  valorpesos: Numeric | null;
}

export interface Cor1440GenEfecto {
  descripcion: string | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  indicadorpf_id: number | null;
  nombre: string | null;
  registradopor_id: number | null;
}

export interface Cor1440GenEfectoOrgsocial {
  efecto_id: number | null;
  orgsocial_id: number | null;
}

export interface Cor1440GenEfectoRespuestafor {
  efecto_id: number | null;
  respuestafor_id: number | null;
}

export interface Cor1440GenFinanciador {
  created_at: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenFinanciadorProyectofinanciero {
  financiador_id: number;
  proyectofinanciero_id: number;
}

export interface Cor1440GenFormularioMindicadorpf {
  formulario_id: Int8;
  mindicadorpf_id: Int8;
}

export interface Cor1440GenFormularioTipoindicador {
  formulario_id: number;
  tipoindicador_id: number;
}

export interface Cor1440GenIndicadorpf {
  id: Generated<Int8>;
  indicador: string;
  numero: string;
  objetivopf_id: number | null;
  proyectofinanciero_id: number | null;
  resultadopf_id: number | null;
  tipoindicador_id: number | null;
}

export interface Cor1440GenInforme {
  avances: string | null;
  columnafecha: boolean | null;
  columnanombre: boolean | null;
  columnaobjetivo: boolean | null;
  columnapoblacion: boolean | null;
  columnaproyecto: boolean | null;
  columnaresponsable: boolean | null;
  columnatipo: boolean | null;
  contextoexterno: string | null;
  contextointerno: string | null;
  created_at: Timestamp;
  dificultades: string | null;
  filtroactividadarea: number | null;
  filtrofechafin: Timestamp;
  filtrofechaini: Timestamp;
  filtrooficina: number | null;
  filtropoa: number | null;
  filtroproyecto: number | null;
  filtroproyectofinanciero: number | null;
  filtroresponsable: number | null;
  id: Generated<number>;
  logros: string | null;
  recomendaciones: string | null;
  titulo: string;
  updated_at: Timestamp;
}

export interface Cor1440GenInformeauditoria {
  created_at: Timestamp;
  detalle: string | null;
  devoluciones: boolean | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinanciero_id: number;
  seguimiento: string | null;
  updated_at: Timestamp;
}

export interface Cor1440GenInformefinanciero {
  created_at: Timestamp;
  detalle: string | null;
  devoluciones: boolean | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinanciero_id: number;
  seguimiento: string | null;
  updated_at: Timestamp;
}

export interface Cor1440GenInformenarrativo {
  created_at: Timestamp;
  detalle: string | null;
  devoluciones: boolean | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinanciero_id: number;
  seguimiento: string | null;
  updated_at: Timestamp;
}

export interface Cor1440GenMindicadorpf {
  created_at: Timestamp;
  descd1: string | null;
  descd2: string | null;
  descd3: string | null;
  formulacion: string | null;
  frecuenciaanual: string | null;
  funcionresultado: string | null;
  id: Generated<Int8>;
  indicadorpf_id: number;
  medircon: number | null;
  meta: number | null;
  proyectofinanciero_id: number;
  updated_at: Timestamp;
}

export interface Cor1440GenObjetivopf {
  id: Generated<Int8>;
  numero: string;
  objetivo: string;
  proyectofinanciero_id: number | null;
}

export interface Cor1440GenPlantillahcmProyectofinanciero {
  plantillahcm_id: number | null;
  proyectofinanciero_id: number | null;
}

export interface Cor1440GenPmindicadorpf {
  acciones: string | null;
  analisis: string | null;
  created_at: Timestamp;
  datosmedicion: Json | null;
  dmed1: number | null;
  dmed2: number | null;
  dmed3: number | null;
  fecha: Timestamp | null;
  ffin: Timestamp | null;
  finicio: Timestamp | null;
  id: Generated<Int8>;
  meta: number | null;
  mindicadorpf_id: number;
  plazo: string | null;
  porcump: number | null;
  resind: number | null;
  resindicador: Json | null;
  responsables: string | null;
  restiempo: string | null;
  rutaevidencia: string | null;
  updated_at: Timestamp;
  urlev1: string | null;
  urlev2: string | null;
  urlev3: string | null;
}

export interface Cor1440GenProyecto {
  created_at: Timestamp | null;
  fechacierre: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  fechainicio: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  resultados: string | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenProyectofinanciero {
  altImagen: string | null;
  aporteotrosej: number | null;
  aportepropioej: number | null;
  centrocosto: string | null;
  compromisos: string | null;
  conBilletera: boolean | null;
  created_at: Timestamp | null;
  creditoImagen: string | null;
  creditosMd: string | null;
  dificultad: Generated<string | null>;
  enlaceImagen: string | null;
  estado: Generated<string | null>;
  fechaaprobacion: Timestamp | null;
  fechacierre: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  fechaformulacion: Timestamp | null;
  fechainicio: Timestamp | null;
  fechaliquidacion: Timestamp | null;
  id: Generated<number>;
  idioma: Generated<string>;
  imagen: string | null;
  monto: Numeric | null;
  montoej: number | null;
  nombre: string | null;
  observaciones: string | null;
  poromision: boolean | null;
  porPagar: number | null;
  prefijoRuta: string | null;
  presupuestototalej: number | null;
  responsable_id: number | null;
  resumenMd: string | null;
  saldoaejecutarp: Numeric | null;
  sectorapc_id: number | null;
  sinBilletera: boolean | null;
  subtitulo: string | null;
  tasaej: number | null;
  tipomoneda_id: number | null;
  titulo: string | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenProyectofinancieroUsuario {
  created_at: Timestamp;
  id: Generated<Int8>;
  proyectofinanciero_id: number;
  updated_at: Timestamp;
  usuario_id: number | null;
}

export interface Cor1440GenProyectoProyectofinanciero {
  proyecto_id: number;
  proyectofinanciero_id: number;
}

export interface Cor1440GenRangoedadac {
  created_at: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  limiteinferior: number | null;
  limitesuperior: number | null;
  nombre: string | null;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenResultadopf {
  id: Generated<Int8>;
  numero: string;
  objetivopf_id: number | null;
  proyectofinanciero_id: number | null;
  resultado: string;
}

export interface Cor1440GenSectorapc {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface Cor1440GenTipoindicador {
  created_at: Timestamp | null;
  descd1: string | null;
  descd2: string | null;
  descd3: string | null;
  descd4: string | null;
  espcampos: string | null;
  espfuncionmedir: string | null;
  esptipometa: string | null;
  espvalidaciones: string | null;
  espvaloresomision: string | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  medircon: number | null;
  nombre: string | null;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface Cor1440GenTipomoneda {
  codiso4217: string;
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  pais_id: number | null;
  simbolo: string | null;
  updated_at: Timestamp;
}

export interface CourseUsuario {
  amountscholarship: Numeric | null;
  created_at: Timestamp | null;
  guidespoints: Numeric | null;
  percentagecompleted: Numeric | null;
  points: number;
  proyectofinanciero_id: number;
  updated_at: Timestamp | null;
  usuario_id: number;
}

export interface GuideUsuario {
  actividadpf_id: number;
  amountpaid: number;
  created_at: Timestamp | null;
  points: number;
  profilescore: number;
  updated_at: Timestamp | null;
  usuario_id: number;
}

export interface Heb412GenCampohc {
  columna: string;
  doc_id: number;
  fila: number | null;
  id: Generated<number>;
  nombrecampo: string;
}

export interface Heb412GenCampoplantillahcm {
  columna: string | null;
  id: Generated<number>;
  nombrecampo: string | null;
  plantillahcm_id: number | null;
}

export interface Heb412GenCampoplantillahcr {
  columna: string | null;
  fila: number | null;
  id: Generated<Int8>;
  nombrecampo: string | null;
  plantillahcr_id: number | null;
}

export interface Heb412GenCarpetaexclusiva {
  carpeta: string | null;
  created_at: Timestamp;
  grupo_id: number | null;
  id: Generated<Int8>;
  updated_at: Timestamp;
}

export interface Heb412GenDoc {
  adjunto_content_type: string | null;
  adjunto_file_name: string | null;
  adjunto_file_size: number | null;
  adjunto_updated_at: Timestamp | null;
  created_at: Timestamp;
  descripcion: string | null;
  dirpapa: number | null;
  filainicial: number | null;
  fuente: string | null;
  id: Generated<number>;
  licencia: string | null;
  nombre: string | null;
  nombremenu: string | null;
  ruta: string | null;
  tdoc_id: number | null;
  tdoc_type: string | null;
  tipodoc: string | null;
  updated_at: Timestamp;
  url: string | null;
  vista: string | null;
}

export interface Heb412GenFormularioPlantillahcm {
  formulario_id: number | null;
  plantillahcm_id: number | null;
}

export interface Heb412GenFormularioPlantillahcr {
  formulario_id: number | null;
  id: Generated<Int8>;
  plantillahcr_id: number | null;
}

export interface Heb412GenPlantilladoc {
  fuente: string | null;
  id: Generated<Int8>;
  licencia: string | null;
  nombremenu: string | null;
  ruta: string | null;
  vista: string | null;
}

export interface Heb412GenPlantillahcm {
  filainicial: number;
  fuente: string | null;
  id: Generated<number>;
  licencia: string | null;
  nombremenu: string;
  ruta: string;
  vista: string;
}

export interface Heb412GenPlantillahcr {
  fuente: string | null;
  id: Generated<Int8>;
  licencia: string | null;
  nombremenu: string | null;
  ruta: string | null;
  vista: string | null;
}

export interface Mr519GenCampo {
  ancho: number | null;
  ayudauso: string | null;
  columna: number | null;
  fila: number | null;
  formulario_id: number;
  id: Generated<Int8>;
  nombre: string;
  nombreinterno: string | null;
  obligatorio: boolean | null;
  tablabasica: string | null;
  tipo: Generated<number>;
}

export interface Mr519GenEncuestapersona {
  adurl: string | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  persona_id: number | null;
  planencuesta_id: number | null;
  respuestafor_id: number | null;
}

export interface Mr519GenEncuestausuario {
  fecha: Timestamp | null;
  fechafin: Timestamp | null;
  fechainicio: Timestamp;
  id: Generated<Int8>;
  respuestafor_id: number | null;
  usuario_id: number;
}

export interface Mr519GenFormulario {
  id: Generated<Int8>;
  nombre: string;
  nombreinterno: string | null;
}

export interface Mr519GenOpcioncs {
  campo_id: number;
  id: Generated<Int8>;
  nombre: string;
  valor: string;
}

export interface Mr519GenPlanencuesta {
  adurl: string | null;
  created_at: Timestamp;
  fechafin: Timestamp | null;
  fechaini: Timestamp | null;
  formulario_id: number | null;
  id: Generated<Int8>;
  plantillacorreoinv_id: number | null;
  updated_at: Timestamp;
}

export interface Mr519GenRespuestafor {
  fechacambio: Timestamp;
  fechaini: Timestamp;
  formulario_id: number | null;
  id: Generated<Int8>;
}

export interface Mr519GenValorcampo {
  campo_id: number;
  id: Generated<Int8>;
  respuestafor_id: number;
  valor: string | null;
  valorjson: Json | null;
}

export interface MsipAnexo {
  adjunto_content_type: string;
  adjunto_file_name: string;
  adjunto_file_size: number;
  adjunto_updated_at: Timestamp | null;
  created_at: Timestamp | null;
  descripcion: string | null;
  id: Generated<number>;
  updated_at: Timestamp | null;
}

export interface MsipBitacora {
  created_at: Timestamp;
  detalle: Json | null;
  fecha: Timestamp;
  id: Generated<Int8>;
  ip: string | null;
  modelo: string | null;
  modelo_id: number | null;
  operacion: string | null;
  params: string | null;
  updated_at: Timestamp;
  url: string | null;
  usuario_id: number | null;
}

export interface MsipCentropoblado {
  cplocal_cod: number | null;
  created_at: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  municipio_id: number | null;
  nombre: string;
  observaciones: string | null;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  tcentropoblado_id: Generated<string>;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface MsipCentropobladoHistvigencia {
  centropoblado_id: number | null;
  cplocal_cod: number | null;
  id: Generated<Int8>;
  nombre: string | null;
  observaciones: string | null;
  tcentropoblado_id: string | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipDepartamento {
  catiso: string | null;
  codiso: string | null;
  codreg: number | null;
  created_at: Timestamp | null;
  deplocal_cod: number | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  nombre: string;
  observaciones: string | null;
  pais_id: Generated<number>;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface MsipDepartamentoHistvigencia {
  catiso: number | null;
  codiso: number | null;
  codreg: number | null;
  departamento_id: number | null;
  deplocal_cod: number | null;
  id: Generated<Int8>;
  nombre: string | null;
  observaciones: string | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipEstadosol {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipEtiqueta {
  created_at: Timestamp | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface MsipEtiquetaMunicipio {
  etiqueta_id: Int8;
  municipio_id: Int8;
}

export interface MsipEtiquetaPersona {
  created_at: Timestamp;
  etiqueta_id: number;
  fecha: Timestamp;
  id: Generated<Int8>;
  observaciones: string | null;
  persona_id: number;
  updated_at: Timestamp;
  usuario_id: number;
}

export interface MsipEtnia {
  created_at: Timestamp;
  descripcion: string | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipFuenteprensa {
  created_at: Timestamp;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface MsipGrupo {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipGrupoper {
  anotaciones: string | null;
  id: Generated<Int8>;
  nombre: string;
}

export interface MsipGrupoUsuario {
  grupo_id: Int8;
  usuario_id: Int8;
}

export interface MsipMundepSinorden {
  idlocal: number | null;
  nombre: string | null;
}

export interface MsipMunicipio {
  codreg: number | null;
  created_at: Timestamp | null;
  departamento_id: number | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  munlocal_cod: number | null;
  nombre: string;
  observaciones: string | null;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  tipomun: string | null;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface MsipMunicipioHistvigencia {
  codreg: number | null;
  id: Generated<Int8>;
  municipio_id: number | null;
  munlocal_cod: number | null;
  nombre: string | null;
  observaciones: string | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipOficina {
  created_at: Timestamp | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface MsipOrgsocial {
  created_at: Timestamp;
  direccion: string | null;
  fax: string | null;
  fechadeshabilitacion: Timestamp | null;
  grupoper_id: number;
  id: Generated<Int8>;
  pais_id: number | null;
  telefono: string | null;
  tipoorg_id: Generated<number>;
  updated_at: Timestamp;
  web: string | null;
}

export interface MsipOrgsocialPersona {
  cargo: string | null;
  correo: string | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  orgsocial_id: number | null;
  perfilorgsocial_id: number | null;
  persona_id: number;
  updated_at: Timestamp;
}

export interface MsipOrgsocialSectororgsocial {
  orgsocial_id: number | null;
  sectororgsocial_id: number | null;
}

export interface MsipPais {
  alfa2: string | null;
  alfa3: string | null;
  codiso: number | null;
  created_at: Timestamp | null;
  div1: string | null;
  div2: string | null;
  div3: string | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  nombre: string;
  nombreiso_espanol: string;
  nombreiso_frances: string | null;
  nombreiso_ingles: string | null;
  observaciones: string | null;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface MsipPaisHistvigencia {
  alfa2: string | null;
  alfa3: string | null;
  codcambio: string | null;
  codiso: number | null;
  id: Generated<Int8>;
  pais_id: number | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipPerfilorgsocial {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipPersona {
  anionac: number | null;
  apellidos: string;
  centropoblado_id: number | null;
  created_at: Timestamp | null;
  departamento_id: number | null;
  dianac: number | null;
  etnia_id: Generated<number>;
  id: Generated<number>;
  mesnac: number | null;
  municipio_id: number | null;
  nacionalde: number | null;
  nombres: string;
  numerodocumento: string | null;
  pais_id: number | null;
  sexo: Generated<string>;
  tdocumento_id: number | null;
  updated_at: Timestamp | null;
}

export interface MsipPersonaTrelacion {
  created_at: Timestamp | null;
  id: Generated<number>;
  observaciones: string | null;
  persona1: number;
  persona2: number;
  trelacion_id: Generated<string>;
  updated_at: Timestamp | null;
}

export interface MsipSectororgsocial {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipSolicitud {
  created_at: Timestamp;
  estadosol_id: number | null;
  fecha: Timestamp;
  id: Generated<Int8>;
  solicitud: string | null;
  updated_at: Timestamp;
  usuario_id: number;
}

export interface MsipSolicitudUsuarionotificar {
  solicitud_id: number | null;
  usuarionotificar_id: number | null;
}

export interface MsipTcentropoblado {
  created_at: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: string;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface MsipTdocumento {
  ayuda: string | null;
  created_at: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  formatoregex: string | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  sigla: string;
  updated_at: Timestamp | null;
}

export interface MsipTema {
  alerta_exito_fondo: string | null;
  alerta_exito_fuente: string | null;
  alerta_problema_fondo: string | null;
  alerta_problema_fuente: string | null;
  btn_accion_fondo_fin: string | null;
  btn_accion_fondo_ini: string | null;
  btn_accion_fuente: string | null;
  btn_peligro_fondo_fin: string | null;
  btn_peligro_fondo_ini: string | null;
  btn_peligro_fuente: string | null;
  btn_primario_fondo_fin: string | null;
  btn_primario_fondo_ini: string | null;
  btn_primario_fuente: string | null;
  color_flota_subitem_fondo: string | null;
  color_flota_subitem_fuente: string | null;
  color_fuente: string | null;
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  fondo: string | null;
  fondo_lista: string | null;
  id: Generated<Int8>;
  nav_fin: string | null;
  nav_fuente: string | null;
  nav_ini: string | null;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipTipoorg {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipTrelacion {
  created_at: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: string;
  inverso: string | null;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface MsipTrivalente {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface MsipTsitio {
  created_at: Timestamp | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp | null;
}

export interface MsipUbicacion {
  centropoblado_id: number | null;
  created_at: Timestamp | null;
  departamento_id: number | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  lugar: string | null;
  municipio_id: number | null;
  pais_id: Generated<number | null>;
  sitio: string | null;
  tsitio_id: Generated<number>;
  updated_at: Timestamp | null;
}

export interface MsipUbicacionpre {
  centropoblado_id: number | null;
  created_at: Timestamp;
  departamento_id: number | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  latitud: number | null;
  longitud: number | null;
  lugar: string | null;
  municipio_id: number | null;
  nombre: string;
  nombre_sin_pais: string | null;
  observaciones: string | null;
  pais_id: number;
  sitio: string | null;
  tsitio_id: number | null;
  updated_at: Timestamp;
  vereda_id: number | null;
}

export interface MsipVereda {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  latitud: number | null;
  longitud: number | null;
  municipio_id: number | null;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
  verlocal_cod: number | null;
}

export interface Nonce {
  created_at: Timestamp;
  id: Generated<Int8>;
  nonce: string | null;
  updated_at: Timestamp;
}

export interface Religion {
  created_at: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updated_at: Timestamp;
}

export interface SchemaMigrations {
  version: string;
}

export interface Ubitransactions {
  amount: Numeric;
  date: Timestamp;
  hash: string;
  id: Generated<number>;
  wallet: string;
}

export interface Userevent {
  created_at: Timestamp;
  event_data: Json | null;
  event_type: string;
  id: Generated<Int8>;
  usuario_id: number | null;
}

export interface Usuario {
  created_at: Timestamp | null;
  current_sign_in_at: Timestamp | null;
  current_sign_in_ip: string | null;
  descripcion: string | null;
  email: Generated<string>;
  encrypted_password: Generated<string>;
  failed_attempts: Generated<number | null>;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  foto_content_type: string | null;
  foto_file_name: string | null;
  foto_file_size: Int8 | null;
  foto_updated_at: Timestamp | null;
  id: Generated<number>;
  idioma: Generated<string>;
  last_sign_in_at: Timestamp | null;
  last_sign_in_ip: string | null;
  lastgooddollarverification: Timestamp | null;
  learningscore: number | null;
  locked_at: Timestamp | null;
  nombre: string | null;
  nusuario: string;
  oficina_id: number | null;
  pais_id: number | null;
  passport_name: string | null;
  passport_nationality: number | null;
  password: Generated<string>;
  profilescore: number | null;
  religion_id: number | null;
  remember_created_at: Timestamp | null;
  reset_password_sent_at: Timestamp | null;
  reset_password_token: string | null;
  rol: Generated<number | null>;
  sign_in_count: Generated<number>;
  tema_id: number | null;
  unlock_token: string | null;
  updated_at: Timestamp | null;
}

export interface DB {
  ar_internal_metadata: ArInternalMetadata;
  billetera_usuario: BilleteraUsuario;
  cor1440_gen_actividad: Cor1440GenActividad;
  cor1440_gen_actividad_actividadpf: Cor1440GenActividadActividadpf;
  cor1440_gen_actividad_actividadtipo: Cor1440GenActividadActividadtipo;
  cor1440_gen_actividad_anexo: Cor1440GenActividadAnexo;
  cor1440_gen_actividad_orgsocial: Cor1440GenActividadOrgsocial;
  cor1440_gen_actividad_proyecto: Cor1440GenActividadProyecto;
  cor1440_gen_actividad_proyectofinanciero: Cor1440GenActividadProyectofinanciero;
  cor1440_gen_actividad_rangoedadac: Cor1440GenActividadRangoedadac;
  cor1440_gen_actividad_respuestafor: Cor1440GenActividadRespuestafor;
  cor1440_gen_actividad_usuario: Cor1440GenActividadUsuario;
  cor1440_gen_actividadarea: Cor1440GenActividadarea;
  cor1440_gen_actividadareas_actividad: Cor1440GenActividadareasActividad;
  cor1440_gen_actividadpf: Cor1440GenActividadpf;
  cor1440_gen_actividadpf_mindicadorpf: Cor1440GenActividadpfMindicadorpf;
  cor1440_gen_actividadtipo: Cor1440GenActividadtipo;
  cor1440_gen_actividadtipo_formulario: Cor1440GenActividadtipoFormulario;
  cor1440_gen_anexo_efecto: Cor1440GenAnexoEfecto;
  cor1440_gen_anexo_proyectofinanciero: Cor1440GenAnexoProyectofinanciero;
  cor1440_gen_asistencia: Cor1440GenAsistencia;
  cor1440_gen_beneficiariopf: Cor1440GenBeneficiariopf;
  cor1440_gen_caracterizacionpersona: Cor1440GenCaracterizacionpersona;
  cor1440_gen_caracterizacionpf: Cor1440GenCaracterizacionpf;
  cor1440_gen_datointermedioti: Cor1440GenDatointermedioti;
  cor1440_gen_datointermedioti_pmindicadorpf: Cor1440GenDatointermediotiPmindicadorpf;
  cor1440_gen_desembolso: Cor1440GenDesembolso;
  cor1440_gen_efecto: Cor1440GenEfecto;
  cor1440_gen_efecto_orgsocial: Cor1440GenEfectoOrgsocial;
  cor1440_gen_efecto_respuestafor: Cor1440GenEfectoRespuestafor;
  cor1440_gen_financiador: Cor1440GenFinanciador;
  cor1440_gen_financiador_proyectofinanciero: Cor1440GenFinanciadorProyectofinanciero;
  cor1440_gen_formulario_mindicadorpf: Cor1440GenFormularioMindicadorpf;
  cor1440_gen_formulario_tipoindicador: Cor1440GenFormularioTipoindicador;
  cor1440_gen_indicadorpf: Cor1440GenIndicadorpf;
  cor1440_gen_informe: Cor1440GenInforme;
  cor1440_gen_informeauditoria: Cor1440GenInformeauditoria;
  cor1440_gen_informefinanciero: Cor1440GenInformefinanciero;
  cor1440_gen_informenarrativo: Cor1440GenInformenarrativo;
  cor1440_gen_mindicadorpf: Cor1440GenMindicadorpf;
  cor1440_gen_objetivopf: Cor1440GenObjetivopf;
  cor1440_gen_plantillahcm_proyectofinanciero: Cor1440GenPlantillahcmProyectofinanciero;
  cor1440_gen_pmindicadorpf: Cor1440GenPmindicadorpf;
  cor1440_gen_proyecto: Cor1440GenProyecto;
  cor1440_gen_proyecto_proyectofinanciero: Cor1440GenProyectoProyectofinanciero;
  cor1440_gen_proyectofinanciero: Cor1440GenProyectofinanciero;
  cor1440_gen_proyectofinanciero_usuario: Cor1440GenProyectofinancieroUsuario;
  cor1440_gen_rangoedadac: Cor1440GenRangoedadac;
  cor1440_gen_resultadopf: Cor1440GenResultadopf;
  cor1440_gen_sectorapc: Cor1440GenSectorapc;
  cor1440_gen_tipoindicador: Cor1440GenTipoindicador;
  cor1440_gen_tipomoneda: Cor1440GenTipomoneda;
  course_usuario: CourseUsuario;
  guide_usuario: GuideUsuario;
  heb412_gen_campohc: Heb412GenCampohc;
  heb412_gen_campoplantillahcm: Heb412GenCampoplantillahcm;
  heb412_gen_campoplantillahcr: Heb412GenCampoplantillahcr;
  heb412_gen_carpetaexclusiva: Heb412GenCarpetaexclusiva;
  heb412_gen_doc: Heb412GenDoc;
  heb412_gen_formulario_plantillahcm: Heb412GenFormularioPlantillahcm;
  heb412_gen_formulario_plantillahcr: Heb412GenFormularioPlantillahcr;
  heb412_gen_plantilladoc: Heb412GenPlantilladoc;
  heb412_gen_plantillahcm: Heb412GenPlantillahcm;
  heb412_gen_plantillahcr: Heb412GenPlantillahcr;
  mr519_gen_campo: Mr519GenCampo;
  mr519_gen_encuestapersona: Mr519GenEncuestapersona;
  mr519_gen_encuestausuario: Mr519GenEncuestausuario;
  mr519_gen_formulario: Mr519GenFormulario;
  mr519_gen_opcioncs: Mr519GenOpcioncs;
  mr519_gen_planencuesta: Mr519GenPlanencuesta;
  mr519_gen_respuestafor: Mr519GenRespuestafor;
  mr519_gen_valorcampo: Mr519GenValorcampo;
  msip_anexo: MsipAnexo;
  msip_bitacora: MsipBitacora;
  msip_centropoblado: MsipCentropoblado;
  msip_centropoblado_histvigencia: MsipCentropobladoHistvigencia;
  msip_departamento: MsipDepartamento;
  msip_departamento_histvigencia: MsipDepartamentoHistvigencia;
  msip_estadosol: MsipEstadosol;
  msip_etiqueta: MsipEtiqueta;
  msip_etiqueta_municipio: MsipEtiquetaMunicipio;
  msip_etiqueta_persona: MsipEtiquetaPersona;
  msip_etnia: MsipEtnia;
  msip_fuenteprensa: MsipFuenteprensa;
  msip_grupo: MsipGrupo;
  msip_grupo_usuario: MsipGrupoUsuario;
  msip_grupoper: MsipGrupoper;
  msip_mundep_sinorden: MsipMundepSinorden;
  msip_municipio: MsipMunicipio;
  msip_municipio_histvigencia: MsipMunicipioHistvigencia;
  msip_oficina: MsipOficina;
  msip_orgsocial: MsipOrgsocial;
  msip_orgsocial_persona: MsipOrgsocialPersona;
  msip_orgsocial_sectororgsocial: MsipOrgsocialSectororgsocial;
  msip_pais: MsipPais;
  msip_pais_histvigencia: MsipPaisHistvigencia;
  msip_perfilorgsocial: MsipPerfilorgsocial;
  msip_persona: MsipPersona;
  msip_persona_trelacion: MsipPersonaTrelacion;
  msip_sectororgsocial: MsipSectororgsocial;
  msip_solicitud: MsipSolicitud;
  msip_solicitud_usuarionotificar: MsipSolicitudUsuarionotificar;
  msip_tcentropoblado: MsipTcentropoblado;
  msip_tdocumento: MsipTdocumento;
  msip_tema: MsipTema;
  msip_tipoorg: MsipTipoorg;
  msip_trelacion: MsipTrelacion;
  msip_trivalente: MsipTrivalente;
  msip_tsitio: MsipTsitio;
  msip_ubicacion: MsipUbicacion;
  msip_ubicacionpre: MsipUbicacionpre;
  msip_vereda: MsipVereda;
  nonce: Nonce;
  religion: Religion;
  schema_migrations: SchemaMigrations;
  ubitransactions: Ubitransactions;
  userevent: Userevent;
  usuario: Usuario;
}
