/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ArInternalMetadata {
  createdAt: Timestamp;
  key: string;
  updatedAt: Timestamp;
  value: string | null;
}

export interface BilleteraUsuario {
  answerFib: string | null;
  billetera: string;
  createdAt: Timestamp;
  id: Generated<Int8>;
  nonce: string | null;
  nonceExpiresAt: Timestamp | null;
  token: string | null;
  updatedAt: Timestamp;
  usuarioId: number;
}

export interface Cor1440GenActividad {
  createdAt: Timestamp | null;
  fecha: Timestamp;
  id: Generated<number>;
  lugar: string | null;
  minutos: number | null;
  nombre: string | null;
  objetivo: string | null;
  observaciones: string | null;
  oficinaId: number;
  resultado: string | null;
  updatedAt: Timestamp | null;
  usuarioId: number;
}

export interface Cor1440GenActividadActividadpf {
  actividadId: number;
  actividadpfId: number;
}

export interface Cor1440GenActividadActividadtipo {
  actividadId: number | null;
  actividadtipoId: number | null;
}

export interface Cor1440GenActividadAnexo {
  actividadId: number;
  anexoId: number;
  id: Generated<number>;
}

export interface Cor1440GenActividadarea {
  createdAt: Timestamp | null;
  fechacreacion: Generated<Timestamp | null>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenActividadareasActividad {
  actividadareaId: number | null;
  actividadId: number | null;
  createdAt: Timestamp | null;
  id: Generated<number>;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenActividadOrgsocial {
  actividadId: Int8;
  orgsocialId: Int8;
}

export interface Cor1440GenActividadpf {
  actividadtipoId: number | null;
  descripcion: string | null;
  formularioId: number | null;
  heredadeId: number | null;
  id: Generated<number>;
  nombrecorto: string | null;
  proyectofinancieroId: number | null;
  resultadopfId: number | null;
  sufijoRuta: string | null;
  titulo: string | null;
}

export interface Cor1440GenActividadpfMindicadorpf {
  actividadpfId: number | null;
  mindicadorpfId: number | null;
}

export interface Cor1440GenActividadProyecto {
  actividadId: number | null;
  id: Generated<number>;
  proyectoId: number | null;
}

export interface Cor1440GenActividadProyectofinanciero {
  actividadId: number;
  id: Generated<number>;
  proyectofinancieroId: number;
}

export interface Cor1440GenActividadRangoedadac {
  actividadId: number | null;
  createdAt: Timestamp | null;
  fl: number | null;
  fr: number | null;
  id: Generated<number>;
  ml: number | null;
  mr: number | null;
  rangoedadacId: number | null;
  s: number | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenActividadRespuestafor {
  actividadId: number;
  respuestaforId: number;
}

export interface Cor1440GenActividadtipo {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  listadoasistencia: boolean | null;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface Cor1440GenActividadtipoFormulario {
  actividadtipoId: number;
  formularioId: number;
}

export interface Cor1440GenActividadUsuario {
  actividadId: number;
  usuarioId: number;
}

export interface Cor1440GenAnexoEfecto {
  anexoId: number | null;
  efectoId: number | null;
  id: Generated<Int8>;
}

export interface Cor1440GenAnexoProyectofinanciero {
  anexoId: number | null;
  id: Generated<Int8>;
  proyectofinancieroId: number | null;
}

export interface Cor1440GenAsistencia {
  actividadId: number;
  externo: boolean | null;
  id: Generated<Int8>;
  orgsocialId: number | null;
  perfilorgsocialId: number | null;
  personaId: number;
  rangoedadacId: number | null;
}

export interface Cor1440GenBeneficiariopf {
  personaId: number | null;
  proyectofinancieroId: number | null;
}

export interface Cor1440GenCaracterizacionpersona {
  id: Generated<Int8>;
  personaId: number;
  respuestaforId: number;
  ulteditorId: number;
}

export interface Cor1440GenCaracterizacionpf {
  formularioId: number | null;
  proyectofinancieroId: number | null;
}

export interface Cor1440GenDatointermedioti {
  filtro: string | null;
  funcion: string | null;
  id: Generated<Int8>;
  mindicadorpfId: number | null;
  nombre: string;
  nombreinterno: string | null;
  tipoindicadorId: number | null;
}

export interface Cor1440GenDatointermediotiPmindicadorpf {
  datointermediotiId: number;
  id: Generated<Int8>;
  pmindicadorpfId: number;
  rutaevidencia: string | null;
  valor: number | null;
}

export interface Cor1440GenDesembolso {
  createdAt: Timestamp;
  detalle: string | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinancieroId: number;
  updatedAt: Timestamp;
  valorpesos: Numeric | null;
}

export interface Cor1440GenEfecto {
  descripcion: string | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  indicadorpfId: number | null;
  nombre: string | null;
  registradoporId: number | null;
}

export interface Cor1440GenEfectoOrgsocial {
  efectoId: number | null;
  orgsocialId: number | null;
}

export interface Cor1440GenEfectoRespuestafor {
  efectoId: number | null;
  respuestaforId: number | null;
}

export interface Cor1440GenFinanciador {
  createdAt: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenFinanciadorProyectofinanciero {
  financiadorId: number;
  proyectofinancieroId: number;
}

export interface Cor1440GenFormularioMindicadorpf {
  formularioId: Int8;
  mindicadorpfId: Int8;
}

export interface Cor1440GenFormularioTipoindicador {
  formularioId: number;
  tipoindicadorId: number;
}

export interface Cor1440GenIndicadorpf {
  id: Generated<Int8>;
  indicador: string;
  numero: string;
  objetivopfId: number | null;
  proyectofinancieroId: number | null;
  resultadopfId: number | null;
  tipoindicadorId: number | null;
}

export interface Cor1440GenInforme {
  avances: string | null;
  columnafecha: boolean | null;
  columnanombre: boolean | null;
  columnaobjetivo: boolean | null;
  columnapoblacion: boolean | null;
  columnaproyecto: boolean | null;
  columnaresponsable: boolean | null;
  columnatipo: boolean | null;
  contextoexterno: string | null;
  contextointerno: string | null;
  createdAt: Timestamp;
  dificultades: string | null;
  filtroactividadarea: number | null;
  filtrofechafin: Timestamp;
  filtrofechaini: Timestamp;
  filtrooficina: number | null;
  filtropoa: number | null;
  filtroproyecto: number | null;
  filtroproyectofinanciero: number | null;
  filtroresponsable: number | null;
  id: Generated<number>;
  logros: string | null;
  recomendaciones: string | null;
  titulo: string;
  updatedAt: Timestamp;
}

export interface Cor1440GenInformeauditoria {
  createdAt: Timestamp;
  detalle: string | null;
  devoluciones: boolean | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinancieroId: number;
  seguimiento: string | null;
  updatedAt: Timestamp;
}

export interface Cor1440GenInformefinanciero {
  createdAt: Timestamp;
  detalle: string | null;
  devoluciones: boolean | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinancieroId: number;
  seguimiento: string | null;
  updatedAt: Timestamp;
}

export interface Cor1440GenInformenarrativo {
  createdAt: Timestamp;
  detalle: string | null;
  devoluciones: boolean | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  proyectofinancieroId: number;
  seguimiento: string | null;
  updatedAt: Timestamp;
}

export interface Cor1440GenMindicadorpf {
  createdAt: Timestamp;
  descd1: string | null;
  descd2: string | null;
  descd3: string | null;
  formulacion: string | null;
  frecuenciaanual: string | null;
  funcionresultado: string | null;
  id: Generated<Int8>;
  indicadorpfId: number;
  medircon: number | null;
  meta: number | null;
  proyectofinancieroId: number;
  updatedAt: Timestamp;
}

export interface Cor1440GenObjetivopf {
  id: Generated<Int8>;
  numero: string;
  objetivo: string;
  proyectofinancieroId: number | null;
}

export interface Cor1440GenPlantillahcmProyectofinanciero {
  plantillahcmId: number | null;
  proyectofinancieroId: number | null;
}

export interface Cor1440GenPmindicadorpf {
  acciones: string | null;
  analisis: string | null;
  createdAt: Timestamp;
  datosmedicion: Json | null;
  dmed1: number | null;
  dmed2: number | null;
  dmed3: number | null;
  fecha: Timestamp | null;
  ffin: Timestamp | null;
  finicio: Timestamp | null;
  id: Generated<Int8>;
  meta: number | null;
  mindicadorpfId: number;
  plazo: string | null;
  porcump: number | null;
  resind: number | null;
  resindicador: Json | null;
  responsables: string | null;
  restiempo: string | null;
  rutaevidencia: string | null;
  updatedAt: Timestamp;
  urlev1: string | null;
  urlev2: string | null;
  urlev3: string | null;
}

export interface Cor1440GenProyecto {
  createdAt: Timestamp | null;
  fechacierre: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  fechainicio: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  resultados: string | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenProyectofinanciero {
  altImagen: string | null;
  aporteotrosej: number | null;
  aportepropioej: number | null;
  centrocosto: string | null;
  chainId: Generated<number | null>;
  compromisos: string | null;
  conBilletera: boolean | null;
  contractAddress: string | null;
  createdAt: Timestamp | null;
  creditoImagen: string | null;
  creditosMd: string | null;
  dificultad: Generated<string | null>;
  enlaceImagen: string | null;
  estado: Generated<string | null>;
  fechaaprobacion: Timestamp | null;
  fechacierre: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  fechaformulacion: Timestamp | null;
  fechainicio: Timestamp | null;
  fechaliquidacion: Timestamp | null;
  id: Generated<number>;
  idioma: Generated<string>;
  imagen: string | null;
  monto: Numeric | null;
  montoej: number | null;
  nombre: string | null;
  observaciones: string | null;
  poromision: boolean | null;
  porPagar: number | null;
  prefijoRuta: string | null;
  presupuestototalej: number | null;
  responsableId: number | null;
  resumenMd: string | null;
  saldoaejecutarp: Numeric | null;
  sectorapcId: number | null;
  sinBilletera: boolean | null;
  subtitulo: string | null;
  tasaej: number | null;
  tipomonedaId: number | null;
  titulo: string | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenProyectofinancieroUsuario {
  createdAt: Timestamp;
  id: Generated<Int8>;
  proyectofinancieroId: number;
  updatedAt: Timestamp;
  usuarioId: number | null;
}

export interface Cor1440GenProyectoProyectofinanciero {
  proyectofinancieroId: number;
  proyectoId: number;
}

export interface Cor1440GenRangoedadac {
  createdAt: Timestamp | null;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  limiteinferior: number | null;
  limitesuperior: number | null;
  nombre: string | null;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenResultadopf {
  id: Generated<Int8>;
  numero: string;
  objetivopfId: number | null;
  proyectofinancieroId: number | null;
  resultado: string;
}

export interface Cor1440GenSectorapc {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface Cor1440GenTipoindicador {
  createdAt: Timestamp | null;
  descd1: string | null;
  descd2: string | null;
  descd3: string | null;
  descd4: string | null;
  espcampos: string | null;
  espfuncionmedir: string | null;
  esptipometa: string | null;
  espvalidaciones: string | null;
  espvaloresomision: string | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  medircon: number | null;
  nombre: string | null;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface Cor1440GenTipomoneda {
  codiso4217: string;
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  paisId: number | null;
  simbolo: string | null;
  updatedAt: Timestamp;
}

export interface CredentialEmission {
  chainId: Generated<string>;
  courseId: number;
  emittedAt: Generated<Timestamp>;
  hash: string | null;
  id: Generated<number>;
  isPremium: Generated<boolean>;
  tokenId: number;
  usuarioId: number;
}

export interface CredentialMetadata {
  chainId: Generated<string>;
  imageUrl: string;
  isPremium: Generated<boolean | null>;
  isSoulbound: Generated<boolean | null>;
  name: string;
  site: string;
  tokenId: number;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface GuideUsuario {
  actividadpfId: number;
  amountpaid: number;
  createdAt: Timestamp | null;
  points: number;
  profilescore: number;
  updatedAt: Timestamp | null;
  usuarioId: number;
}

export interface Heb412GenCampohc {
  columna: string;
  docId: number;
  fila: number | null;
  id: Generated<number>;
  nombrecampo: string;
}

export interface Heb412GenCampoplantillahcm {
  columna: string | null;
  id: Generated<number>;
  nombrecampo: string | null;
  plantillahcmId: number | null;
}

export interface Heb412GenCampoplantillahcr {
  columna: string | null;
  fila: number | null;
  id: Generated<Int8>;
  nombrecampo: string | null;
  plantillahcrId: number | null;
}

export interface Heb412GenCarpetaexclusiva {
  carpeta: string | null;
  createdAt: Timestamp;
  grupoId: number | null;
  id: Generated<Int8>;
  updatedAt: Timestamp;
}

export interface Heb412GenDoc {
  adjuntoContentType: string | null;
  adjuntoFileName: string | null;
  adjuntoFileSize: number | null;
  adjuntoUpdatedAt: Timestamp | null;
  createdAt: Timestamp;
  descripcion: string | null;
  dirpapa: number | null;
  filainicial: number | null;
  fuente: string | null;
  id: Generated<number>;
  licencia: string | null;
  nombre: string | null;
  nombremenu: string | null;
  ruta: string | null;
  tdocId: number | null;
  tdocType: string | null;
  tipodoc: string | null;
  updatedAt: Timestamp;
  url: string | null;
  vista: string | null;
}

export interface Heb412GenFormularioPlantillahcm {
  formularioId: number | null;
  plantillahcmId: number | null;
}

export interface Heb412GenFormularioPlantillahcr {
  formularioId: number | null;
  id: Generated<Int8>;
  plantillahcrId: number | null;
}

export interface Heb412GenPlantilladoc {
  fuente: string | null;
  id: Generated<Int8>;
  licencia: string | null;
  nombremenu: string | null;
  ruta: string | null;
  vista: string | null;
}

export interface Heb412GenPlantillahcm {
  filainicial: number;
  fuente: string | null;
  id: Generated<number>;
  licencia: string | null;
  nombremenu: string;
  ruta: string;
  vista: string;
}

export interface Heb412GenPlantillahcr {
  fuente: string | null;
  id: Generated<Int8>;
  licencia: string | null;
  nombremenu: string | null;
  ruta: string | null;
  vista: string | null;
}

export interface Mr519GenCampo {
  ancho: number | null;
  ayudauso: string | null;
  columna: number | null;
  fila: number | null;
  formularioId: number;
  id: Generated<Int8>;
  nombre: string;
  nombreinterno: string | null;
  obligatorio: boolean | null;
  tablabasica: string | null;
  tipo: Generated<number>;
}

export interface Mr519GenEncuestapersona {
  adurl: string | null;
  fecha: Timestamp | null;
  id: Generated<Int8>;
  personaId: number | null;
  planencuestaId: number | null;
  respuestaforId: number | null;
}

export interface Mr519GenEncuestausuario {
  fecha: Timestamp | null;
  fechafin: Timestamp | null;
  fechainicio: Timestamp;
  id: Generated<Int8>;
  respuestaforId: number | null;
  usuarioId: number;
}

export interface Mr519GenFormulario {
  id: Generated<Int8>;
  nombre: string;
  nombreinterno: string | null;
}

export interface Mr519GenOpcioncs {
  campoId: number;
  id: Generated<Int8>;
  nombre: string;
  valor: string;
}

export interface Mr519GenPlanencuesta {
  adurl: string | null;
  createdAt: Timestamp;
  fechafin: Timestamp | null;
  fechaini: Timestamp | null;
  formularioId: number | null;
  id: Generated<Int8>;
  plantillacorreoinvId: number | null;
  updatedAt: Timestamp;
}

export interface Mr519GenRespuestafor {
  fechacambio: Timestamp;
  fechaini: Timestamp;
  formularioId: number | null;
  id: Generated<Int8>;
}

export interface Mr519GenValorcampo {
  campoId: number;
  id: Generated<Int8>;
  respuestaforId: number;
  valor: string | null;
  valorjson: Json | null;
}

export interface MsipAnexo {
  adjuntoContentType: string;
  adjuntoFileName: string;
  adjuntoFileSize: number;
  adjuntoUpdatedAt: Timestamp | null;
  createdAt: Timestamp | null;
  descripcion: string | null;
  id: Generated<number>;
  updatedAt: Timestamp | null;
}

export interface MsipBitacora {
  createdAt: Timestamp;
  detalle: Json | null;
  fecha: Timestamp;
  id: Generated<Int8>;
  ip: string | null;
  modelo: string | null;
  modeloId: number | null;
  operacion: string | null;
  params: string | null;
  updatedAt: Timestamp;
  url: string | null;
  usuarioId: number | null;
}

export interface MsipCentropoblado {
  cplocalCod: number | null;
  createdAt: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  municipioId: number | null;
  nombre: string;
  observaciones: string | null;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  tcentropobladoId: Generated<string>;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updatedAt: Timestamp | null;
}

export interface MsipCentropobladoHistvigencia {
  centropobladoId: number | null;
  cplocalCod: number | null;
  id: Generated<Int8>;
  nombre: string | null;
  observaciones: string | null;
  tcentropobladoId: string | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipDepartamento {
  catiso: string | null;
  codiso: string | null;
  codreg: number | null;
  createdAt: Timestamp | null;
  deplocalCod: number | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  nombre: string;
  observaciones: string | null;
  paisId: Generated<number>;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updatedAt: Timestamp | null;
}

export interface MsipDepartamentoHistvigencia {
  catiso: number | null;
  codiso: number | null;
  codreg: number | null;
  departamentoId: number | null;
  deplocalCod: number | null;
  id: Generated<Int8>;
  nombre: string | null;
  observaciones: string | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipEstadosol {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipEtiqueta {
  createdAt: Timestamp | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface MsipEtiquetaMunicipio {
  etiquetaId: Int8;
  municipioId: Int8;
}

export interface MsipEtiquetaPersona {
  createdAt: Timestamp;
  etiquetaId: number;
  fecha: Timestamp;
  id: Generated<Int8>;
  observaciones: string | null;
  personaId: number;
  updatedAt: Timestamp;
  usuarioId: number;
}

export interface MsipEtnia {
  createdAt: Timestamp;
  descripcion: string | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipFuenteprensa {
  createdAt: Timestamp;
  fechacreacion: Timestamp | null;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string | null;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface MsipGrupo {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipGrupoper {
  anotaciones: string | null;
  id: Generated<Int8>;
  nombre: string;
}

export interface MsipGrupoUsuario {
  grupoId: Int8;
  usuarioId: Int8;
}

export interface MsipMundepSinorden {
  idlocal: number | null;
  nombre: string | null;
}

export interface MsipMunicipio {
  codreg: number | null;
  createdAt: Timestamp | null;
  departamentoId: number | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  munlocalCod: number | null;
  nombre: string;
  observaciones: string | null;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  tipomun: string | null;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updatedAt: Timestamp | null;
}

export interface MsipMunicipioHistvigencia {
  codreg: number | null;
  id: Generated<Int8>;
  municipioId: number | null;
  munlocalCod: number | null;
  nombre: string | null;
  observaciones: string | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipOficina {
  createdAt: Timestamp | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface MsipOrgsocial {
  createdAt: Timestamp;
  direccion: string | null;
  fax: string | null;
  fechadeshabilitacion: Timestamp | null;
  grupoperId: number;
  id: Generated<Int8>;
  paisId: number | null;
  telefono: string | null;
  tipoorgId: Generated<number>;
  updatedAt: Timestamp;
  web: string | null;
}

export interface MsipOrgsocialPersona {
  cargo: string | null;
  correo: string | null;
  createdAt: Timestamp;
  id: Generated<Int8>;
  orgsocialId: number | null;
  perfilorgsocialId: number | null;
  personaId: number;
  updatedAt: Timestamp;
}

export interface MsipOrgsocialSectororgsocial {
  orgsocialId: number | null;
  sectororgsocialId: number | null;
}

export interface MsipPais {
  alfa2: string | null;
  alfa3: string | null;
  codiso: number | null;
  createdAt: Timestamp | null;
  div1: string | null;
  div2: string | null;
  div3: string | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  nombre: string;
  nombreisoEspanol: string;
  nombreisoFrances: string | null;
  nombreisoIngles: string | null;
  observaciones: string | null;
  svgcdalto: number | null;
  svgcdancho: number | null;
  svgcdx: number | null;
  svgcdy: number | null;
  svgrotx: number | null;
  svgroty: number | null;
  svgruta: string | null;
  ultvigenciafin: Timestamp | null;
  ultvigenciaini: Timestamp | null;
  updatedAt: Timestamp | null;
}

export interface MsipPaisHistvigencia {
  alfa2: string | null;
  alfa3: string | null;
  codcambio: string | null;
  codiso: number | null;
  id: Generated<Int8>;
  paisId: number | null;
  vigenciafin: Timestamp;
  vigenciaini: Timestamp | null;
}

export interface MsipPerfilorgsocial {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipPersona {
  anionac: number | null;
  apellidos: string;
  centropobladoId: number | null;
  createdAt: Timestamp | null;
  departamentoId: number | null;
  dianac: number | null;
  etniaId: Generated<number>;
  id: Generated<number>;
  mesnac: number | null;
  municipioId: number | null;
  nacionalde: number | null;
  nombres: string;
  numerodocumento: string | null;
  paisId: number | null;
  sexo: Generated<string>;
  tdocumentoId: number | null;
  updatedAt: Timestamp | null;
}

export interface MsipPersonaTrelacion {
  createdAt: Timestamp | null;
  id: Generated<number>;
  observaciones: string | null;
  persona1: number;
  persona2: number;
  trelacionId: Generated<string>;
  updatedAt: Timestamp | null;
}

export interface MsipSectororgsocial {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipSolicitud {
  createdAt: Timestamp;
  estadosolId: number | null;
  fecha: Timestamp;
  id: Generated<Int8>;
  solicitud: string | null;
  updatedAt: Timestamp;
  usuarioId: number;
}

export interface MsipSolicitudUsuarionotificar {
  solicitudId: number | null;
  usuarionotificarId: number | null;
}

export interface MsipTcentropoblado {
  createdAt: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: string;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface MsipTdocumento {
  ayuda: string | null;
  createdAt: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  formatoregex: string | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  sigla: string;
  updatedAt: Timestamp | null;
}

export interface MsipTema {
  alertaExitoFondo: string | null;
  alertaExitoFuente: string | null;
  alertaProblemaFondo: string | null;
  alertaProblemaFuente: string | null;
  btnAccionFondoFin: string | null;
  btnAccionFondoIni: string | null;
  btnAccionFuente: string | null;
  btnPeligroFondoFin: string | null;
  btnPeligroFondoIni: string | null;
  btnPeligroFuente: string | null;
  btnPrimarioFondoFin: string | null;
  btnPrimarioFondoIni: string | null;
  btnPrimarioFuente: string | null;
  colorFlotaSubitemFondo: string | null;
  colorFlotaSubitemFuente: string | null;
  colorFuente: string | null;
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  fondo: string | null;
  fondoLista: string | null;
  id: Generated<Int8>;
  navFin: string | null;
  navFuente: string | null;
  navIni: string | null;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipTipoorg {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipTrelacion {
  createdAt: Timestamp | null;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: string;
  inverso: string | null;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface MsipTrivalente {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface MsipTsitio {
  createdAt: Timestamp | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp | null;
}

export interface MsipUbicacion {
  centropobladoId: number | null;
  createdAt: Timestamp | null;
  departamentoId: number | null;
  id: Generated<number>;
  latitud: number | null;
  longitud: number | null;
  lugar: string | null;
  municipioId: number | null;
  paisId: Generated<number | null>;
  sitio: string | null;
  tsitioId: Generated<number>;
  updatedAt: Timestamp | null;
}

export interface MsipUbicacionpre {
  centropobladoId: number | null;
  createdAt: Timestamp;
  departamentoId: number | null;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  latitud: number | null;
  longitud: number | null;
  lugar: string | null;
  municipioId: number | null;
  nombre: string;
  nombreSinPais: string | null;
  observaciones: string | null;
  paisId: number;
  sitio: string | null;
  tsitioId: number | null;
  updatedAt: Timestamp;
  veredaId: number | null;
}

export interface MsipVereda {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  latitud: number | null;
  longitud: number | null;
  municipioId: number | null;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
  verlocalCod: number | null;
}

export interface Nonce {
  createdAt: Timestamp;
  id: Generated<Int8>;
  nonce: string | null;
  updatedAt: Timestamp;
}

export interface Religion {
  createdAt: Timestamp;
  fechacreacion: Timestamp;
  fechadeshabilitacion: Timestamp | null;
  id: Generated<Int8>;
  nombre: string;
  observaciones: string | null;
  updatedAt: Timestamp;
}

export interface SchemaMigrations {
  version: string;
}

export interface SiteNonces {
  availableLearningpoints: Generated<number>;
  lastNonce: Generated<number>;
  site: string;
  updatedAt: Timestamp | null;
}

export interface Transaction {
  cantidad: Generated<Numeric>;
  categoria: string | null;
  crypto: string;
  descripcion: string | null;
  fecha: Timestamp;
  fechaActualizacion: Generated<Timestamp>;
  fechaCreacion: Generated<Timestamp>;
  hash: string | null;
  id: Generated<number>;
  impactoBalance: Numeric;
  metadata: Json | null;
  sincronizado: Generated<boolean>;
  subcategoria: string | null;
  tipo: string;
  usuarioId: number;
  wallet: string;
}

export interface Userevent {
  createdAt: Timestamp;
  eventData: Json | null;
  eventType: string;
  id: Generated<Int8>;
  usuarioId: number | null;
}

export interface Usuario {
  createdAt: Timestamp | null;
  currentSignInAt: Timestamp | null;
  currentSignInIp: string | null;
  descripcion: string | null;
  email: Generated<string>;
  encryptedPassword: Generated<string>;
  excluirLeaderboard: Generated<boolean | null>;
  failedAttempts: Generated<number | null>;
  fechacreacion: Generated<Timestamp>;
  fechadeshabilitacion: Timestamp | null;
  fotoContentType: string | null;
  fotoFileName: string | null;
  fotoFileSize: Int8 | null;
  fotoUpdatedAt: Timestamp | null;
  id: Generated<number>;
  idioma: Generated<string>;
  lastgooddollarverification: Timestamp | null;
  lastSignInAt: Timestamp | null;
  lastSignInIp: string | null;
  learningscore: number | null;
  lockedAt: Timestamp | null;
  nombre: string | null;
  nusuario: string;
  oficinaId: number | null;
  paisId: number | null;
  passportName: string | null;
  passportNationality: number | null;
  password: Generated<string>;
  profilescore: number | null;
  religionId: number | null;
  rememberCreatedAt: Timestamp | null;
  resetPasswordSentAt: Timestamp | null;
  resetPasswordToken: string | null;
  rol: Generated<number | null>;
  signInCount: Generated<number>;
  temaId: number | null;
  unlockToken: string | null;
  updatedAt: Timestamp | null;
}

export interface ViewUserScores {
  learningscore: number | null;
  profilescore: number | null;
  userId: number | null;
}

export interface DB {
  arInternalMetadata: ArInternalMetadata;
  billeteraUsuario: BilleteraUsuario;
  cor1440GenActividad: Cor1440GenActividad;
  cor1440GenActividadActividadpf: Cor1440GenActividadActividadpf;
  cor1440GenActividadActividadtipo: Cor1440GenActividadActividadtipo;
  cor1440GenActividadAnexo: Cor1440GenActividadAnexo;
  cor1440GenActividadarea: Cor1440GenActividadarea;
  cor1440GenActividadareasActividad: Cor1440GenActividadareasActividad;
  cor1440GenActividadOrgsocial: Cor1440GenActividadOrgsocial;
  cor1440GenActividadpf: Cor1440GenActividadpf;
  cor1440GenActividadpfMindicadorpf: Cor1440GenActividadpfMindicadorpf;
  cor1440GenActividadProyecto: Cor1440GenActividadProyecto;
  cor1440GenActividadProyectofinanciero: Cor1440GenActividadProyectofinanciero;
  cor1440GenActividadRangoedadac: Cor1440GenActividadRangoedadac;
  cor1440GenActividadRespuestafor: Cor1440GenActividadRespuestafor;
  cor1440GenActividadtipo: Cor1440GenActividadtipo;
  cor1440GenActividadtipoFormulario: Cor1440GenActividadtipoFormulario;
  cor1440GenActividadUsuario: Cor1440GenActividadUsuario;
  cor1440GenAnexoEfecto: Cor1440GenAnexoEfecto;
  cor1440GenAnexoProyectofinanciero: Cor1440GenAnexoProyectofinanciero;
  cor1440GenAsistencia: Cor1440GenAsistencia;
  cor1440GenBeneficiariopf: Cor1440GenBeneficiariopf;
  cor1440GenCaracterizacionpersona: Cor1440GenCaracterizacionpersona;
  cor1440GenCaracterizacionpf: Cor1440GenCaracterizacionpf;
  cor1440GenDatointermedioti: Cor1440GenDatointermedioti;
  cor1440GenDatointermediotiPmindicadorpf: Cor1440GenDatointermediotiPmindicadorpf;
  cor1440GenDesembolso: Cor1440GenDesembolso;
  cor1440GenEfecto: Cor1440GenEfecto;
  cor1440GenEfectoOrgsocial: Cor1440GenEfectoOrgsocial;
  cor1440GenEfectoRespuestafor: Cor1440GenEfectoRespuestafor;
  cor1440GenFinanciador: Cor1440GenFinanciador;
  cor1440GenFinanciadorProyectofinanciero: Cor1440GenFinanciadorProyectofinanciero;
  cor1440GenFormularioMindicadorpf: Cor1440GenFormularioMindicadorpf;
  cor1440GenFormularioTipoindicador: Cor1440GenFormularioTipoindicador;
  cor1440GenIndicadorpf: Cor1440GenIndicadorpf;
  cor1440GenInforme: Cor1440GenInforme;
  cor1440GenInformeauditoria: Cor1440GenInformeauditoria;
  cor1440GenInformefinanciero: Cor1440GenInformefinanciero;
  cor1440GenInformenarrativo: Cor1440GenInformenarrativo;
  cor1440GenMindicadorpf: Cor1440GenMindicadorpf;
  cor1440GenObjetivopf: Cor1440GenObjetivopf;
  cor1440GenPlantillahcmProyectofinanciero: Cor1440GenPlantillahcmProyectofinanciero;
  cor1440GenPmindicadorpf: Cor1440GenPmindicadorpf;
  cor1440GenProyecto: Cor1440GenProyecto;
  cor1440GenProyectofinanciero: Cor1440GenProyectofinanciero;
  cor1440GenProyectofinancieroUsuario: Cor1440GenProyectofinancieroUsuario;
  cor1440GenProyectoProyectofinanciero: Cor1440GenProyectoProyectofinanciero;
  cor1440GenRangoedadac: Cor1440GenRangoedadac;
  cor1440GenResultadopf: Cor1440GenResultadopf;
  cor1440GenSectorapc: Cor1440GenSectorapc;
  cor1440GenTipoindicador: Cor1440GenTipoindicador;
  cor1440GenTipomoneda: Cor1440GenTipomoneda;
  credentialEmission: CredentialEmission;
  credentialMetadata: CredentialMetadata;
  guideUsuario: GuideUsuario;
  heb412GenCampohc: Heb412GenCampohc;
  heb412GenCampoplantillahcm: Heb412GenCampoplantillahcm;
  heb412GenCampoplantillahcr: Heb412GenCampoplantillahcr;
  heb412GenCarpetaexclusiva: Heb412GenCarpetaexclusiva;
  heb412GenDoc: Heb412GenDoc;
  heb412GenFormularioPlantillahcm: Heb412GenFormularioPlantillahcm;
  heb412GenFormularioPlantillahcr: Heb412GenFormularioPlantillahcr;
  heb412GenPlantilladoc: Heb412GenPlantilladoc;
  heb412GenPlantillahcm: Heb412GenPlantillahcm;
  heb412GenPlantillahcr: Heb412GenPlantillahcr;
  mr519GenCampo: Mr519GenCampo;
  mr519GenEncuestapersona: Mr519GenEncuestapersona;
  mr519GenEncuestausuario: Mr519GenEncuestausuario;
  mr519GenFormulario: Mr519GenFormulario;
  mr519GenOpcioncs: Mr519GenOpcioncs;
  mr519GenPlanencuesta: Mr519GenPlanencuesta;
  mr519GenRespuestafor: Mr519GenRespuestafor;
  mr519GenValorcampo: Mr519GenValorcampo;
  msipAnexo: MsipAnexo;
  msipBitacora: MsipBitacora;
  msipCentropoblado: MsipCentropoblado;
  msipCentropobladoHistvigencia: MsipCentropobladoHistvigencia;
  msipDepartamento: MsipDepartamento;
  msipDepartamentoHistvigencia: MsipDepartamentoHistvigencia;
  msipEstadosol: MsipEstadosol;
  msipEtiqueta: MsipEtiqueta;
  msipEtiquetaMunicipio: MsipEtiquetaMunicipio;
  msipEtiquetaPersona: MsipEtiquetaPersona;
  msipEtnia: MsipEtnia;
  msipFuenteprensa: MsipFuenteprensa;
  msipGrupo: MsipGrupo;
  msipGrupoper: MsipGrupoper;
  msipGrupoUsuario: MsipGrupoUsuario;
  msipMundepSinorden: MsipMundepSinorden;
  msipMunicipio: MsipMunicipio;
  msipMunicipioHistvigencia: MsipMunicipioHistvigencia;
  msipOficina: MsipOficina;
  msipOrgsocial: MsipOrgsocial;
  msipOrgsocialPersona: MsipOrgsocialPersona;
  msipOrgsocialSectororgsocial: MsipOrgsocialSectororgsocial;
  msipPais: MsipPais;
  msipPaisHistvigencia: MsipPaisHistvigencia;
  msipPerfilorgsocial: MsipPerfilorgsocial;
  msipPersona: MsipPersona;
  msipPersonaTrelacion: MsipPersonaTrelacion;
  msipSectororgsocial: MsipSectororgsocial;
  msipSolicitud: MsipSolicitud;
  msipSolicitudUsuarionotificar: MsipSolicitudUsuarionotificar;
  msipTcentropoblado: MsipTcentropoblado;
  msipTdocumento: MsipTdocumento;
  msipTema: MsipTema;
  msipTipoorg: MsipTipoorg;
  msipTrelacion: MsipTrelacion;
  msipTrivalente: MsipTrivalente;
  msipTsitio: MsipTsitio;
  msipUbicacion: MsipUbicacion;
  msipUbicacionpre: MsipUbicacionpre;
  msipVereda: MsipVereda;
  nonce: Nonce;
  religion: Religion;
  schemaMigrations: SchemaMigrations;
  siteNonces: SiteNonces;
  transaction: Transaction;
  userevent: Userevent;
  usuario: Usuario;
  viewUserScores: ViewUserScores;
}
