import { Kysely, sql } from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
  // Crear tabla pais_hdi si no existe
  await sql`
    CREATE TABLE IF NOT EXISTS pais_hdi (
        id SERIAL PRIMARY KEY,
        pais_id INTEGER NOT NULL REFERENCES msip_pais(id),
        year INTEGER NOT NULL,
        hdi DECIMAL(4,3) NOT NULL,
        source VARCHAR(50) DEFAULT 'UNDP',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(pais_id, year)
    )
  `.execute(db)

  // Crear índices
  await sql`CREATE INDEX IF NOT EXISTS idx_pais_hdi_pais_id ON pais_hdi(pais_id)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_pais_hdi_year ON pais_hdi(year)`.execute(db)

  // Insertar datos HDI
  await sql`
    INSERT INTO pais_hdi (pais_id, year, hdi, source, created_at, updated_at)
    VALUES
    (SELECT id FROM msip_pais WHERE alfa3 = 'AFG'), 2023, 0.496, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ALB'), 2023, 0.81, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'DZA'), 2023, 0.763, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'AND'), 2023, 0.913, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'AGO'), 2023, 0.616, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ATG'), 2023, 0.851, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ARG'), 2023, 0.865, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ARM'), 2023, 0.811, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'AUS'), 2023, 0.958, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'AUT'), 2023, 0.93, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'AZE'), 2023, 0.789, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BHS'), 2023, 0.82, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BHR'), 2023, 0.899, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BGD'), 2023, 0.685, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BRB'), 2023, 0.811, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BLR'), 2023, 0.824, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BEL'), 2023, 0.951, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BLZ'), 2023, 0.721, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BEN'), 2023, 0.515, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BTN'), 2023, 0.698, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BOL'), 2023, 0.733, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BIH'), 2023, 0.804, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BWA'), 2023, 0.731, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BRA'), 2023, 0.786, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BRN'), 2023, 0.837, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BGR'), 2023, 0.845, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BFA'), 2023, 0.459, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'BDI'), 2023, 0.439, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KHM'), 2023, 0.606, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CMR'), 2023, 0.588, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CAN'), 2023, 0.939, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CPV'), 2023, 0.668, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CAF'), 2023, 0.414, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TCD'), 2023, 0.416, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CHL'), 2023, 0.878, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CHN'), 2023, 0.797, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'COL'), 2023, 0.788, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'COM'), 2023, 0.603, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'COG'), 2023, 0.649, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CRI'), 2023, 0.833, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CIV'), 2023, 0.582, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'HRV'), 2023, 0.889, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CUB'), 2023, 0.762, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CYP'), 2023, 0.913, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CZE'), 2023, 0.915, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'COD'), 2023, 0.522, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'DNK'), 2023, 0.962, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'DJI'), 2023, 0.513, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'DMA'), 2023, 0.761, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'DOM'), 2023, 0.776, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TLS'), 2023, 0.634, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ECU'), 2023, 0.777, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'EGY'), 2023, 0.754, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SLV'), 2023, 0.678, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GNQ'), 2023, 0.674, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ERI'), 2023, 0.503, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'EST'), 2023, 0.905, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SWZ'), 2023, 0.695, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ETH'), 2023, 0.497, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'FJI'), 2023, 0.731, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'FIN'), 2023, 0.948, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'FRA'), 2023, 0.92, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GAB'), 2023, 0.733, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GMB'), 2023, 0.524, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GEO'), 2023, 0.844, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'DEU'), 2023, 0.959, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GHA'), 2023, 0.628, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GRC'), 2023, 0.908, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GRD'), 2023, 0.791, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GTM'), 2023, 0.662, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GIN'), 2023, 0.5, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GNB'), 2023, 0.514, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GUY'), 2023, 0.776, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'HTI'), 2023, 0.554, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'HND'), 2023, 0.645, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'HKG'), 2023, 0.955, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'HUN'), 2023, 0.87, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ISL'), 2023, 0.972, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'IND'), 2023, 0.685, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'IDN'), 2023, 0.728, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'IRN'), 2023, 0.799, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'IRQ'), 2023, 0.695, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'IRL'), 2023, 0.949, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ISR'), 2023, 0.919, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ITA'), 2023, 0.915, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'JAM'), 2023, 0.72, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'JPN'), 2023, 0.925, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'JOR'), 2023, 0.754, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KAZ'), 2023, 0.837, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KEN'), 2023, 0.628, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KIR'), 2023, 0.644, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KWT'), 2023, 0.852, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KGZ'), 2023, 0.72, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LAO'), 2023, 0.617, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LVA'), 2023, 0.889, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LBN'), 2023, 0.752, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LSO'), 2023, 0.55, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LBR'), 2023, 0.51, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LBY'), 2023, 0.721, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LIE'), 2023, 0.938, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LTU'), 2023, 0.895, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LUX'), 2023, 0.922, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MDG'), 2023, 0.487, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MWI'), 2023, 0.517, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MYS'), 2023, 0.819, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MDV'), 2023, 0.766, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MLI'), 2023, 0.419, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MLT'), 2023, 0.924, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MHL'), 2023, 0.733, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MRT'), 2023, 0.563, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MUS'), 2023, 0.806, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MEX'), 2023, 0.789, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'FSM'), 2023, 0.615, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MDA'), 2023, 0.785, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MNG'), 2023, 0.747, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MNE'), 2023, 0.862, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MAR'), 2023, 0.71, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MOZ'), 2023, 0.493, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MMR'), 2023, 0.609, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NAM'), 2023, 0.665, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NRU'), 2023, 0.703, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NPL'), 2023, 0.622, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NLD'), 2023, 0.955, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NZL'), 2023, 0.938, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NIC'), 2023, 0.706, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NER'), 2023, 0.419, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NGA'), 2023, 0.56, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'MKD'), 2023, 0.815, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'NOR'), 2023, 0.97, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'OMN'), 2023, 0.858, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PAK'), 2023, 0.544, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PLW'), 2023, 0.786, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PSE'), 2023, 0.674, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PAN'), 2023, 0.839, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PNG'), 2023, 0.576, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PRY'), 2023, 0.756, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PER'), 2023, 0.794, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PHL'), 2023, 0.72, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'POL'), 2023, 0.906, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'PRT'), 2023, 0.89, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'QAT'), 2023, 0.886, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ROU'), 2023, 0.845, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'RUS'), 2023, 0.832, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'RWA'), 2023, 0.578, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KNA'), 2023, 0.84, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LCA'), 2023, 0.748, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'VCT'), 2023, 0.798, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'WSM'), 2023, 0.708, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SMR'), 2023, 0.915, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'STP'), 2023, 0.637, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SAU'), 2023, 0.9, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SEN'), 2023, 0.53, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SRB'), 2023, 0.833, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SYC'), 2023, 0.848, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SLE'), 2023, 0.467, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SGP'), 2023, 0.946, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SVK'), 2023, 0.88, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SVN'), 2023, 0.931, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SLB'), 2023, 0.584, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SOM'), 2023, 0.404, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ZAF'), 2023, 0.741, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'KOR'), 2023, 0.937, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SSD'), 2023, 0.388, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ESP'), 2023, 0.918, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'LKA'), 2023, 0.776, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SDN'), 2023, 0.511, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SUR'), 2023, 0.722, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SWE'), 2023, 0.959, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'CHE'), 2023, 0.97, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'SYR'), 2023, 0.564, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TJK'), 2023, 0.691, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TZA'), 2023, 0.555, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'THA'), 2023, 0.798, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TGO'), 2023, 0.571, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TON'), 2023, 0.769, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TTO'), 2023, 0.807, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TUN'), 2023, 0.746, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TUR'), 2023, 0.853, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TKM'), 2023, 0.764, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'TUV'), 2023, 0.689, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'UGA'), 2023, 0.582, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'UKR'), 2023, 0.779, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ARE'), 2023, 0.94, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'GBR'), 2023, 0.946, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'USA'), 2023, 0.938, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'URY'), 2023, 0.862, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'UZB'), 2023, 0.74, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'VUT'), 2023, 0.621, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'VEN'), 2023, 0.709, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'VNM'), 2023, 0.766, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'YEM'), 2023, 0.47, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ZMB'), 2023, 0.595, 'UNDP', NOW(), NOW(),
    (SELECT id FROM msip_pais WHERE alfa3 = 'ZWE'), 2023, 0.598, 'UNDP', NOW(), NOW()
    ON CONFLICT (pais_id, year) DO UPDATE
    SET hdi = EXCLUDED.hdi, updated_at = NOW()
  `.execute(db)
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`DROP TABLE IF EXISTS pais_hdi`.execute(db)
}

