'use client'

import { useEffect } from 'react'

/**
 * Registers the service worker generated by next-pwa (R-#240).
 *
 * next-pwa would do it by itself, but its auto-register injects `register.js`
 * into the webpack `main.js` entry, which does not exist in the App Router: the
 * worker is generated and served while nothing registers it (verified on the dev
 * site on 2026-09-15: `/sw.js` answers 200 while `navigator.serviceWorker
 * .getRegistrations()` is empty). Registering from the app keeps the manifest,
 * the offline caches and installability working.
 *
 * Set `NEXT_PUBLIC_PWA_DISABLE=1` to skip the registration.
 */
export function ServiceWorkerRegistrar() {
  useEffect(() => {
    if (process.env.NEXT_PUBLIC_PWA_DISABLE === '1') return
    // `'serviceWorker' in navigator` no basta: en navegadores sin soporte la
    // propiedad puede existir con valor undefined.
    if (typeof navigator === 'undefined' || !navigator.serviceWorker?.register) return

    navigator.serviceWorker.register('/sw.js').catch((error) => {
      console.info('[pwa] no se pudo registrar el service worker:', error?.message || error)
    })
  }, [])

  return null
}
