// @vitest-environment jsdom
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { render } from '@testing-library/react'
import { ServiceWorkerRegistrar } from '../ServiceWorkerRegistrar'

describe('ServiceWorkerRegistrar (R-#240)', () => {
  const register = vi.fn(() => Promise.resolve({} as ServiceWorkerRegistration))

  beforeEach(() => {
    register.mockClear()
    Object.defineProperty(window.navigator, 'serviceWorker', {
      value: { register },
      configurable: true,
    })
    vi.unstubAllEnvs()
  })

  afterEach(() => {
    vi.unstubAllEnvs()
  })

  it('registers the service worker generated by next-pwa', () => {
    render(<ServiceWorkerRegistrar />)
    expect(register).toHaveBeenCalledWith('/sw.js')
  })

  it('does not register when NEXT_PUBLIC_PWA_DISABLE=1', () => {
    vi.stubEnv('NEXT_PUBLIC_PWA_DISABLE', '1')
    render(<ServiceWorkerRegistrar />)
    expect(register).not.toHaveBeenCalled()
  })

  it('does not blow up when the browser has no service worker support', () => {
    Object.defineProperty(window.navigator, 'serviceWorker', {
      value: undefined,
      configurable: true,
    })
    expect(() => render(<ServiceWorkerRegistrar />)).not.toThrow()
    expect(register).not.toHaveBeenCalled()
  })

  it('survives a rejected registration', async () => {
    register.mockReturnValueOnce(Promise.reject(new Error('offline')))
    expect(() => render(<ServiceWorkerRegistrar />)).not.toThrow()
    await Promise.resolve()
  })
})
